<?php
declare(strict_types = 1);

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace Theolangstraat\Phiki\Service;

use Phiki\Grammar\Grammar;

class PhikiGrammarResolver
{
    /**
     * Map van alle aliassen → Grammar enum
     */
    private const MAP = [
        'abap' => Grammar::Abap,
        'actionscript-3' => Grammar::Actionscript_3,
        'ada' => Grammar::Ada,
        'angular-html' => Grammar::AngularHtml,
        'angular-ts' => Grammar::AngularTs,
        'apache' => Grammar::Apache,
        'apex' => Grammar::Apex,
        'apl' => Grammar::Apl,
        'applescript' => Grammar::Applescript,
        'ara' => Grammar::Ara,
        'asciidoc' => Grammar::Asciidoc,
        'adoc' => Grammar::Asciidoc,
        'asm' => Grammar::Asm,
        'astro' => Grammar::Astro,
        'awk' => Grammar::Awk,
        'ballerina' => Grammar::Ballerina,
        'bat' => Grammar::Bat,
        'batch' => Grammar::Bat,
        'beancount' => Grammar::Beancount,
        'berry' => Grammar::Berry,
        'be' => Grammar::Berry,
        'bibtex' => Grammar::Bibtex,
        'blade' => Grammar::Blade,
        'bsl' => Grammar::Bsl,
        '1c' => Grammar::Bsl,
        'c' => Grammar::C,
        'cadence' => Grammar::Cadence,
        'cdc' => Grammar::Cadence,
        'cairo' => Grammar::Cairo,
        'clarity' => Grammar::Clarity,
        'clojure' => Grammar::Clojure,
        'clj' => Grammar::Clojure,
        'cmake' => Grammar::Cmake,
        'cobol' => Grammar::Cobol,
        'codeowners' => Grammar::Codeowners,
        'codeql' => Grammar::Codeql,
        'ql' => Grammar::Codeql,
        'coffee' => Grammar::Coffee,
        'coffeescript' => Grammar::Coffee,
        'common-lisp' => Grammar::CommonLisp,
        'lisp' => Grammar::CommonLisp,
        'coq' => Grammar::Coq,
        'cpp' => Grammar::Cpp,
        'c++' => Grammar::Cpp,
        'crystal' => Grammar::Crystal,
        'csharp' => Grammar::Csharp,
        'c#' => Grammar::Csharp,
        'cs' => Grammar::Csharp,
        'css' => Grammar::Css,
        'csv' => Grammar::Csv,
        'cue' => Grammar::Cue,
        'cypher' => Grammar::Cypher,
        'cql' => Grammar::Cypher,
        'd' => Grammar::D,
        'dart' => Grammar::Dart,
        'dax' => Grammar::Dax,
        'desktop' => Grammar::Desktop,
        'diff' => Grammar::Diff,
        'docker' => Grammar::Docker,
        'dockerfile' => Grammar::Docker,
        'dotenv' => Grammar::Dotenv,
        'dream-maker' => Grammar::DreamMaker,
        'dm' => Grammar::DreamMaker,
        'edge' => Grammar::Edge,
        'elixir' => Grammar::Elixir,
        'elm' => Grammar::Elm,
        'emacs-lisp' => Grammar::EmacsLisp,
        'elisp' => Grammar::EmacsLisp,
        'erb' => Grammar::Erb,
        'erlang' => Grammar::Erlang,
        'erl' => Grammar::Erlang,
        'fennel' => Grammar::Fennel,
        'fish' => Grammar::Fish,
        'fluent' => Grammar::Fluent,
        'ftl' => Grammar::Fluent,
        'fortran-fixed-form' => Grammar::FortranFixedForm,
        'f' => Grammar::FortranFixedForm,
        'for' => Grammar::FortranFixedForm,
        'f77' => Grammar::FortranFixedForm,
        'fortran-free-form' => Grammar::FortranFreeForm,
        'f90' => Grammar::FortranFreeForm,
        'f95' => Grammar::FortranFreeForm,
        'f03' => Grammar::FortranFreeForm,
        'f08' => Grammar::FortranFreeForm,
        'f18' => Grammar::FortranFreeForm,
        'fsharp' => Grammar::Fsharp,
        'f#' => Grammar::Fsharp,
        'fs' => Grammar::Fsharp,
        'gdresource' => Grammar::Gdresource,
        'gdscript' => Grammar::Gdscript,
        'gdshader' => Grammar::Gdshader,
        'genie' => Grammar::Genie,
        'gherkin' => Grammar::Gherkin,
        'git-commit' => Grammar::GitCommit,
        'git-rebase' => Grammar::GitRebase,
        'gleam' => Grammar::Gleam,
        'glimmer-js' => Grammar::GlimmerJs,
        'gjs' => Grammar::GlimmerJs,
        'glimmer-ts' => Grammar::GlimmerTs,
        'gts' => Grammar::GlimmerTs,
        'glsl' => Grammar::Glsl,
        'gnuplot' => Grammar::Gnuplot,
        'go' => Grammar::Go,
        'graphql' => Grammar::Graphql,
        'gql' => Grammar::Graphql,
        'groovy' => Grammar::Groovy,
        'hack' => Grammar::Hack,
        'haml' => Grammar::Haml,
        'handlebars' => Grammar::Handlebars,
        'hbs' => Grammar::Handlebars,
        'haskell' => Grammar::Haskell,
        'hs' => Grammar::Haskell,
        'haxe' => Grammar::Haxe,
        'hcl' => Grammar::Hcl,
        'hjson' => Grammar::Hjson,
        'hlsl' => Grammar::Hlsl,
        'html' => Grammar::Html,
        'http' => Grammar::Http,
        'ini' => Grammar::Ini,
        'properties' => Grammar::Ini,
        'java' => Grammar::Java,
        'javascript' => Grammar::Javascript,
        'js' => Grammar::Javascript,
        'jinja' => Grammar::Jinja,
        'json' => Grammar::Json,
        'json5' => Grammar::Json5,
        'jsonc' => Grammar::Jsonc,
        'jsonl' => Grammar::Jsonl,
        'jsonnet' => Grammar::Jsonnet,
        'jsx' => Grammar::Jsx,
        'julia' => Grammar::Julia,
        'jl' => Grammar::Julia,
        'kotlin' => Grammar::Kotlin,
        'kt' => Grammar::Kotlin,
        'kts' => Grammar::Kotlin,
        'latex' => Grammar::Latex,
        'less' => Grammar::Less,
        'liquid' => Grammar::Liquid,
        'llvm' => Grammar::Llvm,
        'log' => Grammar::Log,
        'lua' => Grammar::Lua,
        'luau' => Grammar::Luau,
        'make' => Grammar::Make,
        'makefile' => Grammar::Make,
        'markdown' => Grammar::Markdown,
        'md' => Grammar::Markdown,
        'matlab' => Grammar::Matlab,
        'mermaid' => Grammar::Mermaid,
        'mmd' => Grammar::Mermaid,
        'mojo' => Grammar::Mojo,
        'move' => Grammar::Move,
        'nginx' => Grammar::Nginx,
        'nim' => Grammar::Nim,
        'nix' => Grammar::Nix,
        'objective-c' => Grammar::ObjectiveC,
        'objc' => Grammar::ObjectiveC,
        'objective-cpp' => Grammar::ObjectiveCpp,
        'ocaml' => Grammar::Ocaml,
        'pascal' => Grammar::Pascal,
        'perl' => Grammar::Perl,
        'php' => Grammar::Php,
        'plsql' => Grammar::Plsql,
        'postcss' => Grammar::Postcss,
        'powershell' => Grammar::Powershell,
        'ps' => Grammar::Powershell,
        'ps1' => Grammar::Powershell,
        'prolog' => Grammar::Prolog,
        'proto' => Grammar::Proto,
        'protobuf' => Grammar::Proto,
        'pug' => Grammar::Pug,
        'jade' => Grammar::Pug,
        'python' => Grammar::Python,
        'py' => Grammar::Python,
        'qml' => Grammar::Qml,
        'r' => Grammar::R,
        'ruby' => Grammar::Ruby,
        'rb' => Grammar::Ruby,
        'rust' => Grammar::Rust,
        'rs' => Grammar::Rust,
        'sass' => Grammar::Sass,
        'scss' => Grammar::Scss,
        'scala' => Grammar::Scala,
        'shellscript' => Grammar::Shellscript,
        'bash' => Grammar::Shellscript,
        'sh' => Grammar::Shellscript,
        'shell' => Grammar::Shellscript,
        'zsh' => Grammar::Shellscript,
        'sql' => Grammar::Sql,
        'swift' => Grammar::Swift,
        'terraform' => Grammar::Terraform,
        'tf' => Grammar::Terraform,
        'toml' => Grammar::Toml,
        'tsx' => Grammar::Tsx,
        'typescript' => Grammar::Typescript,
        'ts' => Grammar::Typescript,
        'twig' => Grammar::Twig,
        'v' => Grammar::V,
        'vala' => Grammar::Vala,
        'vb' => Grammar::Vb,
        'verilog' => Grammar::Verilog,
        'vhdl' => Grammar::Vhdl,
        'vue' => Grammar::Vue,
        'wasm' => Grammar::Wasm,
        'xml' => Grammar::Xml,
        'yaml' => Grammar::Yaml,
        'yml' => Grammar::Yaml,
        'zig' => Grammar::Zig,
    ];

    public function resolve(string $input): Grammar
    {
        $key = strtolower(trim($input));

        return self::MAP[$key] ?? Grammar::Php;
    }
}
