services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Theolangstraat\Phiki\:
    resource: '../Classes/*'
    exclude: '../Classes/Phiki/'

  Theolangstraat\Phiki\Backend\Preview\CodeSnippetPreviewRenderer:
    tags:
      - name: event.listener
        identifier: 'phiki-backend-preview'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent

  Theolangstraat\Phiki\EventListeners\FlexFormDefaultsListener:
    tags:
      - name: event.listener
        identifier: 'phiki-flexform-defaults'
        event: TYPO3\CMS\Core\Configuration\Event\BeforeFlexFormDataStructureParsedEvent
